### ISSUE TITLE
Alpha 1.0.0 Checklist

### ISSUE THREAD

**Issue by Sancires** [Sancires/Ares#10]
A list of features I would like to be implemented before alpha 1.0.0:

- [ ] Every over-world ore obtainable
- [ ] Every over-world wood type obtainable
- [ ] Every over-world stone variant obtainable
- [ ] Basic carving
- [ ] Different temperature oceans
- [ ] Realistic pipeline / biome order
- [ ] 1.18-esque mountains
- [ ] #2 At the very least, understood
- [ ] #1 Alleviated significantly

**Comment by Sancires** [comment]
Closing, as pack is going to be entirely refactored and refreshed
